"""Inkflip CLI package."""

from .main import EXIT_CANCELLED, EXIT_INCOMPARABLE, EXIT_INVALID_ARGS, EXIT_OK, EXIT_PARTIAL_RUN, EXIT_POLICY_FAILURE, EXIT_READ_FAILURE, main

__all__ = [
    "EXIT_CANCELLED",
    "EXIT_INCOMPARABLE",
    "EXIT_INVALID_ARGS",
    "EXIT_OK",
    "EXIT_PARTIAL_RUN",
    "EXIT_POLICY_FAILURE",
    "EXIT_READ_FAILURE",
    "main",
]
