// TEST-04 — canonical geometry and transform conformance.
//
// Verifies packages/geometry against expected coordinates derived
// INDEPENDENTLY of the implementation: tests/geometry/expected.json is
// generated by derive_expectations.py using exact fractions.Fraction
// arithmetic plus hand-derived closed-form per-rotation equations, and
// additionally anchored on the published numeric example in
// planning/architecture/COORDINATES.md and the executed PDFium probe in
// planning/probes/results/native-probe.json. Expected values are never
// produced by inverting this package's own output.
//
// Fixture ids: F07 (origins-rotation), F08 (userunit), F09 (text
// transform genus — analytic), F10 (missingness genus — analytic).
// Invariants: I02 (occurrence binds page/ordinal/geometry precision),
// I04 (no precise highlight without independently supplied geometry).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

import {
  ContractError,
  apply,
  inverse,
  normalize,
  seal,
  validate,
} from '../../packages/contracts/src/index.ts';
import {
  MIN_POLYGON_AREA,
  backingScale,
  boxPolygon,
  buildPage,
  canonicalSpace,
  chainPage,
  chainPageInverse,
  clipToView,
  compose,
  cropTranslationRecord,
  displayRotation,
  displaySpace,
  displayTransformRecord,
  effectiveViewBox,
  ensureGeometryPage,
  ensurePage,
  makeGeometry,
  makeTransform,
  ocrResizeRecord,
  ocrToCanonical,
  pageToCanonical,
  pageToDisplay,
  pageToOcr,
  pageToRaster,
  pdfUserSpace,
  polygonBounds,
  rasterToCanonical,
  rasterTransformRecord,
  round6,
  signedArea,
  transformPolygon,
  viewportRecord,
  viewportTransform,
} from '../../packages/geometry/src/index.ts';
import { minimalReport } from './report_helper.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const EXPECTED = JSON.parse(
  readFileSync(join(ROOT, 'tests', 'geometry', 'expected.json'), 'utf8'),
);
const MANIFEST = JSON.parse(
  readFileSync(join(ROOT, 'fixtures', 'manifest.json'), 'utf8'),
);
const PROBE = JSON.parse(
  readFileSync(
    join(ROOT, 'planning', 'probes', 'results', 'native-probe.json'),
    'utf8',
  ),
);

const TOL = 1e-5;
const near = (a, b, msg) =>
  assert.ok(
    Math.abs(a - b) <= TOL,
    `${msg}: |${a} - ${b}| = ${Math.abs(a - b)} > ${TOL}pt`,
  );
const nearPt = (a, b, msg) => {
  near(a[0], b[0], `${msg} (x)`);
  near(a[1], b[1], `${msg} (y)`);
};
const nearMat = (a, b, msg) => {
  for (let i = 0; i < 6; i++) near(a[i], b[i], `${msg}[${i}]`);
};
const code = (fn) => {
  try {
    fn();
  } catch (e) {
    if (e instanceof ContractError) return e.code;
    throw e;
  }
  return null;
};

/** Parse the minimal deterministic fixture PDF page dict (read-only). */
function parseFixturePage(relPath) {
  const bytes = readFileSync(join(ROOT, 'fixtures', relPath));
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  const entry = MANIFEST.entries.find((e) => e.path === relPath);
  assert.ok(entry, `${relPath} must be in the fixture manifest`);
  assert.equal(
    sha256,
    entry.sha256,
    `${relPath} bytes diverge from the manifest (original bytes are immutable)`,
  );
  const text = bytes.toString('latin1');
  const m = text.match(
    /\/MediaBox \[([-\d. ]+)\] \/CropBox \[([-\d. ]+)\] \/Rotate (\d+) \/UserUnit ([\d.]+)/,
  );
  assert.ok(m, `${relPath}: page dict not found`);
  const nums = (s) => s.trim().split(/\s+/).map(Number);
  return {
    mediaBox: nums(m[1]),
    cropBox: nums(m[2]),
    rotation: Number(m[3]),
    userUnit: Number(m[4]),
    sha256,
  };
}

function buildFromFixture(relPath) {
  const f = parseFixturePage(relPath);
  return buildPage({
    index: 0,
    mediaBox: f.mediaBox,
    cropBox: f.cropBox,
    userUnit: f.userUnit,
    rotation: f.rotation,
    boxSource: `fixture ${relPath} page dict (sha256 ${f.sha256.slice(0, 12)}…)`,
  });
}

// ---------------------------------------------------------------------------
// F07 — effective view, C, all four rotations, nonzero/negative origins
// ---------------------------------------------------------------------------

for (const name of [
  'geometry-0',
  'geometry-90',
  'geometry-180',
  'geometry-270',
  'geometry-control',
]) {
  test(`F07 ${name}: C/R composition matches independent expectations`, () => {
    const exp = EXPECTED.pages[name];
    const parsed = parseFixturePage(`public/${name}.pdf`);
    // Fixture bytes carry the recipe the expectation was derived from.
    assert.deepEqual(parsed.mediaBox, exp.media_box);
    assert.deepEqual(parsed.cropBox, exp.crop_box);
    assert.equal(parsed.rotation, exp.rotation);
    assert.equal(parsed.userUnit, exp.user_unit);

    const built = buildFromFixture(`public/${name}.pdf`);
    // Effective view = CropBox ∩ MediaBox, applied once.
    assert.deepEqual(built.page.effective_view_box, exp.effective_view);
    nearPt(built.page.canonical_size_pt, exp.canonical_size_pt, 'canonical size');
    nearMat(built.canonical.matrix, exp.C, 'C');
    nearMat(built.canonical.inverse, exp.C_inverse, 'C inverse');
    assert.equal(built.canonical.operation, 'page_box_to_canonical');
    assert.equal(built.canonical.from_space, pdfUserSpace(0));
    assert.equal(built.canonical.to_space, canonicalSpace(0));

    // D = R * C through the package; display size matches the independent
    // derivation AND the executed PDFium probe's render pixel grid
    // (independent anchor: the probe rendered the real bytes).
    nearMat(pageToDisplay(built), exp.D, 'D = R*C');
    const { size: displaySize } = displayRotation(
      built.page.rotation,
      built.page.canonical_size_pt,
    );
    nearPt(displaySize, exp.display_size, 'display size');
    // Independent anchor: the executed PDFium probe rendered these exact
    // bytes; its raster grid at 1px/pt must equal the display size.
    const probeRec = PROBE.records.find((r) => r.fixture === `${name}.pdf`);
    if (probeRec) {
      assert.deepEqual(
        displaySize,
        probeRec.render_pixels,
        'display pt size must equal the probe raster grid at 1px/pt',
      );
    }

    // Every named anchor maps through C/R/S/O to the independently
    // derived coordinates, then recovers to canonical exactly.
    for (const [label, want] of Object.entries(exp.maps)) {
      const p = want.pdf_user;
      nearPt(apply(pageToCanonical(built), p), want.canonical, `${label} canonical`);
      nearPt(apply(pageToDisplay(built), p), want.display, `${label} display`);
      nearPt(
        apply(pageToRaster(built, 1.5), p),
        want.raster_1_5,
        `${label} raster@1.5`,
      );
      nearPt(
        apply(pageToOcr(built, 1.5, [500, 60], [2, 2]), p),
        want.ocr_crop_500_60_k2,
        `${label} ocr`,
      );
      // O = K*T*S*R*C; recover canonical via C * inverse(O).
      const back = apply(
        compose(pageToCanonical(built), inverse(pageToOcr(built, 1.5, [500, 60], [2, 2]))),
        apply(pageToOcr(built, 1.5, [500, 60], [2, 2]), p),
      );
      nearPt(back, want.canonical, `${label} recovered`);
      nearMat(
        compose(pageToCanonical(built), inverse(pageToOcr(built, 1.5, [500, 60], [2, 2]))),
        exp.recover_matrix,
        `${label} recover matrix`,
      );
    }
  });
}

test('F07 rotation corner anchors are independent, not inverted output', () => {
  // The expected corner set is a closed-form anchor per rotation.
  const built = buildFromFixture('public/geometry-90.pdf');
  for (const deg of [0, 90, 180, 270]) {
    const { matrix } = displayRotation(deg, built.page.canonical_size_pt);
    nearPt(
      apply(matrix, [0, 0]),
      EXPECTED.rotation_corner_map[String(deg)],
      `R${deg} origin corner`,
    );
  }
});

test('F07 fixture text anchors map through real fixture bytes', () => {
  // The same "48 220 Td" origin exists in all four rotated fixtures;
  // rotation changes display, not stored canonical coordinates.
  const canonical = {};
  for (const deg of [0, 90, 180, 270]) {
    const built = buildFromFixture(`public/geometry-${deg}.pdf`);
    const exp = EXPECTED.pages[`geometry-${deg}`].maps.text_anchor;
    nearPt(
      apply(pageToCanonical(built), [48, 220]),
      exp.canonical,
      `canonical @${deg}`,
    );
    canonical[deg] = exp.canonical;
    nearPt(apply(pageToDisplay(built), [48, 220]), exp.display, `display @${deg}`);
  }
  assert.ok(
    Object.values(canonical).every((c) => c[0] === 56 && c[1] === 340),
    'canonical storage is rotation-independent',
  );
});

// ---------------------------------------------------------------------------
// F08 — UserUnit applied exactly once
// ---------------------------------------------------------------------------

for (const us of ['0.5', '1', '2', '10']) {
  test(`F08 userunit-${us}: physical size and fiducial, no double scaling`, () => {
    const exp = EXPECTED.userunit[us];
    const u = Number(us);
    const built = buildFromFixture(`development/userunit-${us}.pdf`);
    nearPt(
      built.page.canonical_size_pt,
      exp.canonical_size_pt,
      'canonical size',
    );
    // Canonical size is u * box span exactly once — not u^2, not 1.
    const span = [
      built.page.effective_view_box[2] - built.page.effective_view_box[0],
      built.page.effective_view_box[3] - built.page.effective_view_box[1],
    ];
    nearPt(
      built.page.canonical_size_pt,
      [u * span[0], u * span[1]],
      'single UserUnit application',
    );
    if (u !== 1) {
      assert.notDeepEqual(
        built.page.canonical_size_pt,
        [u * u * span[0], u * u * span[1]],
        'UserUnit must not be applied twice',
      );
    }
    // Fiducial: the fixture's 100x100 user-unit rect at (372,250) maps to
    // the independently derived polygon; physical size is 100u pt.
    const fidPdf = [
      [372, 350],
      [472, 350],
      [472, 250],
      [372, 250],
    ];
    const poly = fidPdf.map((p) => apply(pageToCanonical(built), p));
    for (let i = 0; i < 4; i++) {
      nearPt(poly[i], exp.fiducial_polygon[i], `fiducial vertex ${i}`);
    }
    const bounds = polygonBounds(poly);
    nearPt(
      [bounds[2] - bounds[0], bounds[3] - bounds[1]],
      exp.fiducial_physical_size_pt,
      'fiducial physical size',
    );
    nearPt(
      apply(pageToCanonical(built), [48, 220]),
      exp.text_anchor_canonical,
      'text anchor canonical',
    );
  });
}

test('F08 explicit view path (PDF.js page.view) applies UserUnit once', () => {
  // A reader that reports only the effective view still applies u once.
  const built = buildPage({
    index: 0,
    mediaBox: null,
    cropBox: null,
    viewBox: [0, 0, 520, 400],
    userUnit: 10,
    rotation: 0,
    boxSource: 'reader-reported effective view',
  });
  assert.deepEqual(built.page.canonical_size_pt, [5200, 4000]);
  assert.deepEqual(built.page.media_box, null);
  assert.deepEqual(built.page.crop_box, null);
});

// ---------------------------------------------------------------------------
// Singular / malformed transforms rejected
// ---------------------------------------------------------------------------

test('singular transforms are rejected (determinant <= 1e-12)', () => {
  for (const m of [
    [1, 2, 2, 4, 0, 0], // det = 0
    [0, 0, 0, 0, 10, 10], // det = 0
    [1e-9, 0, 0, 1e-9, 0, 0], // det = 1e-18
    [2e-7, 0, 0, 2e-7, 0, 0], // det = 4e-14
    [1, 1, 2, 2, 0, 0], // proportional rows
  ]) {
    assert.equal(code(() => inverse(m)), 'TRANSFORM', `inverse ${m}`);
    assert.equal(
      code(() =>
        makeTransform({
          id: 't_bad',
          pageIndex: 0,
          fromSpace: 'a',
          toSpace: 'b',
          matrix: m,
          operation: 'raster_scale',
          precision: 'exact',
          source: 'test',
        }),
      ),
      'TRANSFORM',
      `makeTransform ${m}`,
    );
  }
});

test('nonfinite and malformed matrices are rejected', () => {
  for (const m of [
    [1, 0, 0, 1, NaN, 0],
    [1, 0, 0, 1, Infinity, 0],
    [1, 0, 0, 1, 0, -Infinity],
    [1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 0, 0],
    'not-a-matrix',
  ]) {
    const c = code(() =>
      makeTransform({
        id: 't_bad',
        pageIndex: 0,
        fromSpace: 'a',
        toSpace: 'b',
        matrix: m,
        operation: 'raster_scale',
        precision: 'exact',
        source: 'test',
      }),
    );
    assert.ok(c === 'NONFINITE' || c === 'TYPE', `expected rejection, got ${c}`);
  }
});

test('page boxes, rotation and UserUnit reject invalid input', () => {
  const base = {
    index: 0,
    mediaBox: [0, 0, 520, 400],
    cropBox: null,
    userUnit: 1,
    rotation: 0,
    boxSource: 'test',
  };
  assert.equal(
    code(() => buildPage({ ...base, mediaBox: [0, 0, 0, 400] })),
    'GEOMETRY',
  );
  assert.equal(code(() => buildPage({ ...base, userUnit: 0 })), 'GEOMETRY');
  assert.equal(code(() => buildPage({ ...base, userUnit: -2 })), 'GEOMETRY');
  assert.equal(
    code(() => buildPage({ ...base, userUnit: NaN })),
    'GEOMETRY',
  );
  assert.equal(code(() => buildPage({ ...base, rotation: 45 })), 'GEOMETRY');
  assert.equal(code(() => buildPage({ ...base, index: -1 })), 'PAGE');
  // Empty effective view (disjoint crop/media) is unsupported, not guessed.
  assert.equal(
    code(() =>
      buildPage({
        ...base,
        mediaBox: [0, 0, 100, 100],
        cropBox: [200, 200, 300, 300],
      }),
    ),
    'GEOMETRY',
  );
  // Explicit view disagreeing with derived view is a conflict.
  assert.equal(
    code(() =>
      buildPage({ ...base, cropBox: [0, 0, 520, 400], viewBox: [0, 0, 100, 100] }),
    ),
    'GEOMETRY',
  );
});

test('effectiveViewBox is CropBox intersect MediaBox; crop defaults to media', () => {
  assert.deepEqual(
    effectiveViewBox([-20, -30, 520, 420], [20, 40, 500, 390]),
    [20, 40, 500, 390],
  );
  assert.deepEqual(effectiveViewBox([0, 0, 100, 100], null), [0, 0, 100, 100]);
  assert.deepEqual(effectiveViewBox(null, [5, 5, 50, 50]), [5, 5, 50, 50]);
  assert.equal(code(() => effectiveViewBox(null, null)), 'GEOMETRY');
});

// ---------------------------------------------------------------------------
// Precision / schema obedience (I02, I04)
// ---------------------------------------------------------------------------

test('estimated and page_only geometry validate inside a real report', () => {
  const report = minimalReport();
  seal(report); // computes run_key + report_id over the real content
  validate(report); // structural + semantic: pages, transforms, geometry
});

test('precision/polygon conflicts are rejected at build and at validation', () => {
  // I04: page_only/unknown never carry a polygon; exact/estimated must.
  for (const precision of ['page_only', 'unknown']) {
    const g = makeGeometry({
      precision,
      polygon: null,
      transformIds: [],
      basis: 'no precise anchor',
    });
    assert.equal(g.polygon, null);
    assert.equal(g.space, 'canonical_page');
    assert.equal(
      code(() =>
        makeGeometry({
          precision,
          polygon: [
            [0, 0],
            [1, 0],
            [1, 1],
          ],
          transformIds: [],
          basis: 'smuggled polygon',
        }),
      ),
      'GEOMETRY',
      `${precision} must not carry a polygon`,
    );
  }
  for (const precision of ['exact', 'estimated']) {
    assert.equal(
      code(() =>
        makeGeometry({
          precision,
          polygon: null,
          transformIds: [],
          basis: 'missing polygon',
        }),
      ),
      'GEOMETRY',
      `${precision} requires a polygon`,
    );
  }
  // The report validator enforces the same rule on untrusted data.
  const report = minimalReport();
  seal(report);
  report.occurrences[0].geometry.polygon = null; // estimated + null
  assert.equal(code(() => validate(report)), 'GEOMETRY');
});

test('degenerate and malformed polygons are rejected', () => {
  const badPolygons = [
    { polygon: [[0, 0], [1, 0]], code: 'GEOMETRY' }, // <3 vertices
    {
      polygon: [
        [0, 0],
        [0, 0],
        [0, 0],
      ],
      code: 'GEOMETRY', // zero area
    },
    {
      polygon: [
        [0, 0],
        [1e-13, 0],
        [0, 1e-13],
      ],
      code: 'GEOMETRY', // |area| <= 1e-12
    },
    {
      polygon: Array.from({ length: 65 }, (_, i) => [i, i * i]),
      code: 'GEOMETRY', // >64 vertices
    },
    {
      polygon: [
        [0, 0],
        [1, NaN],
        [1, 1],
      ],
      code: 'NONFINITE', // nonfinite vertex
    },
  ];
  for (const { polygon, code: want } of badPolygons) {
    assert.equal(
      code(() =>
        makeGeometry({
          precision: 'exact',
          polygon,
          transformIds: [],
          basis: 'bad polygon',
        }),
      ),
      want,
      `polygon ${JSON.stringify(polygon).slice(0, 60)}`,
    );
  }
  assert.ok(Math.abs(signedArea(boxPolygon([0, 0, 2, 2]))) > MIN_POLYGON_AREA);
});

test('transform ids are schema-shaped and geometry references resolve', () => {
  assert.equal(
    code(() =>
      makeGeometry({
        precision: 'page_only',
        polygon: null,
        transformIds: ['BAD ID'],
        basis: 'x',
      }),
    ),
    'ID',
  );
  const report = minimalReport();
  seal(report);
  report.occurrences[0].geometry.transform_ids = ['t_missing'];
  assert.equal(code(() => validate(report)), 'REFERENCE');
});

// ---------------------------------------------------------------------------
// Page identity (release-blocking)
// ---------------------------------------------------------------------------

test('transform chains refuse to cross pages (correct-page binding)', () => {
  const p0 = buildPage({
    index: 0,
    mediaBox: [0, 0, 520, 400],
    cropBox: null,
    userUnit: 1,
    rotation: 0,
    boxSource: 'page 0',
  });
  const p1 = buildPage({
    index: 1,
    mediaBox: [0, 0, 100, 100],
    cropBox: null,
    userUnit: 1,
    rotation: 0,
    boxSource: 'page 1',
  });
  assert.equal(
    code(() => chainPage([p0.canonical, p1.canonical], 0)),
    'PAGE',
  );
  assert.equal(
    code(() => ensureGeometryPage(
      makeGeometry({
        precision: 'estimated',
        polygon: [
          [0, 0],
          [10, 0],
          [10, 10],
        ],
        transformIds: [p1.canonical.id],
        basis: 'wrong page reference',
      }),
      [p0.canonical, p1.canonical],
      0,
    )),
    'TRANSFORM',
  );
  // Same check inside report validation: geometry on page 0 cannot cite a
  // transform bound to page 1.
  const report = minimalReport();
  const p1b = buildPage({
    index: 1,
    mediaBox: [0, 0, 100, 100],
    cropBox: null,
    userUnit: 1,
    rotation: 0,
    boxSource: 'page 1',
  });
  report.document.page_count = 2;
  report.pages.push(p1b.page);
  report.transforms.push(p1b.canonical);
  report.occurrences[0].geometry.transform_ids = [p1b.canonical.id];
  seal(report);
  assert.equal(code(() => validate(report)), 'TRANSFORM');
});

// ---------------------------------------------------------------------------
// Clipping metadata — source polygons are never deleted or snapped
// ---------------------------------------------------------------------------

test('clipping metadata classifies inside/partial/outside honestly', () => {
  const view = EXPECTED.clip.view;
  const size = [view[2] - view[0], view[3] - view[1]];
  for (const c of EXPECTED.clip.cases) {
    const input = c.polygon.map((p) => [...p]);
    const result = clipToView(input, size);
    assert.equal(result.status, c.status, c.name);
    assert.equal(result.fullyVisible, c.status === 'inside', c.name);
    // Source polygon is preserved verbatim (never moved onto the page).
    assert.deepEqual(result.source, c.polygon, `${c.name} source preserved`);
    if (c.clipped_vertices === null) {
      assert.equal(result.clipped, null, `${c.name} clipped`);
    } else {
      const want = [...c.clipped_vertices].sort((a, b) => a[0] - b[0] || a[1] - b[1]);
      const got = [...result.clipped].sort((a, b) => a[0] - b[0] || a[1] - b[1]);
      assert.deepEqual(got, want, `${c.name} clipped vertices`);
      near(
        Math.abs(signedArea(result.clipped)),
        c.clipped_area,
        `${c.name} clipped area`,
      );
      assert.deepEqual(
        polygonBounds(result.clipped),
        c.clipped_bounds,
        `${c.name} clipped bounds`,
      );
    }
  }
});

test('partial overlap is not full visibility; out-of-crop stays outside', () => {
  const size = [100, 80];
  const partial = clipToView(
    [
      [-20, 10],
      [50, 10],
      [50, 40],
      [-20, 40],
    ],
    size,
  );
  assert.equal(partial.status, 'partial');
  assert.equal(partial.fullyVisible, false);
  // An out-of-crop canonical observation below the view is reported for
  // the outside-view inset, not silently moved onto the page.
  const outside = clipToView(
    [
      [10, 700],
      [90, 700],
      [90, 760],
      [10, 760],
    ],
    size,
  );
  assert.equal(outside.status, 'outside');
  assert.equal(outside.clipped, null);
  assert.deepEqual(outside.source[0], [10, 700]);
});

// ---------------------------------------------------------------------------
// CSS / DPR — correct page, DPR only at the backing canvas
// ---------------------------------------------------------------------------

test('viewport/css math matches independent expectations', () => {
  const anchor = EXPECTED.css.canonical_point;
  for (const c of EXPECTED.css.cases) {
    const v = viewportTransform({ zoom: c.zoom });
    const cssPt = apply(v, anchor);
    nearPt(cssPt, c.css, `css zoom=${c.zoom}`);
    // DPR applies only when crossing to the backing canvas.
    const backing = apply(compose(backingScale(c.dpr), v), anchor);
    nearPt(backing, c.backing, `backing dpr=${c.dpr} zoom=${c.zoom}`);
    // Overlay DOM coordinates are CSS pixels — DPR is never applied twice.
    if (c.dpr !== 1) {
      assert.notDeepEqual(cssPt, c.backing, 'DOM coords must not carry DPR');
    }
  }
});

test('viewport records are contract transforms bound to the right page', () => {
  const built = buildFromFixture('public/geometry-90.pdf');
  const rec = viewportRecord(built.page, 'vp1', { zoom: 2, panX: 5, panY: -3 });
  assert.equal(rec.operation, 'viewport');
  assert.equal(rec.page_index, 0);
  assert.equal(rec.from_space, displaySpace(0));
  assert.equal(rec.to_space, 'css:vp1');
  ensurePage([built.canonical, rec], 0);
  assert.equal(code(() => ensurePage([rec], 1)), 'PAGE');
});

test('stored 6dp rounding keeps overlay error far below the 2px budget', () => {
  // Worst-case analytic bound for the viewer: every stored component is
  // within 5e-7 of the ideal; at max zoom 4 and DPR 3 the induced CSS-px
  // displacement stays orders below the p95<=2px / max<=4px budget.
  const built = buildFromFixture('public/geometry-270.pdf');
  const ideal = [
    2, 0, 0, -2, -40, 780, // C
  ];
  const stored = built.canonical.matrix;
  let worst = 0;
  for (const [px, py] of [
    [20, 40],
    [500, 390],
    [48, 220],
    [-20, -30],
    [520, 420],
  ]) {
    const a = apply(ideal, [px, py]);
    const b = apply(stored, [px, py]);
    worst = Math.max(worst, Math.abs(a[0] - b[0]), Math.abs(a[1] - b[1]));
  }
  assert.ok(
    worst * 4 * 3 <= 2,
    `stored-transform displacement ${worst}pt *12 exceeds 2px`,
  );
});

// ---------------------------------------------------------------------------
// Deterministic round-trip conformance (10,000 sampled points)
// ---------------------------------------------------------------------------

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

test('10,000 deterministic samples round-trip within 1e-5pt', () => {
  const rng = mulberry32(8090); // same seed family as the planning probe
  const uniform = (lo, hi) => lo + (hi - lo) * rng();
  const choice = (xs) => xs[Math.floor(rng() * xs.length)];
  let maxErr = 0;
  let sampledPoints = 0;
  const N = 10000;
  for (let i = 0; i < N; i++) {
    const cx = uniform(-100, 100);
    const cy = uniform(-100, 100);
    const w = uniform(50, 2000);
    const h = uniform(50, 2000);
    const u = choice([0.5, 1, 2, 10]);
    const deg = choice([0, 90, 180, 270]);
    const s = uniform(0.25, 4);
    const built = buildPage({
      index: 0,
      mediaBox: [cx, cy, cx + w, cy + h],
      cropBox: null,
      userUnit: u,
      rotation: deg,
      boxSource: 'sampled round-trip',
    });
    const m = compose(
      [2, 0, 0, 2, -24, -36], // fixed OCR-style crop+resize leg
      pageToRaster(built, s),
    );
    const inv = inverse(m);
    const p = [uniform(cx, cx + w), uniform(cy, cy + h)];
    const back = apply(inv, apply(m, p));
    const err = Math.max(Math.abs(back[0] - p[0]), Math.abs(back[1] - p[1]));
    maxErr = Math.max(maxErr, err);
    sampledPoints++;
    assert.ok(
      err <= TOL,
      `sample ${i} round-trip error ${err}pt exceeds ${TOL}pt`,
    );
  }
  assert.equal(sampledPoints, 10000, 'full deterministic population executed');
  assert.ok(Number.isFinite(maxErr) && maxErr <= TOL, 'maximum error within budget');
});

test('composed chains and their stored inverses agree within bounds', () => {
  const built = buildFromFixture('public/geometry-270.pdf');
  const display = displayTransformRecord(built.page);
  const raster = rasterTransformRecord(built.page, 1.5, 'r270');
  const crop = cropTranslationRecord(built.page, 'r270', 'o270', 500, 60);
  const resize = ocrResizeRecord(built.page, 'o270', 2);
  const chain = [built.canonical, display, raster, crop, resize];
  const fwd = chainPage(chain, 0);
  const bwd = chainPageInverse(chain, 0);
  const p = [48, 220];
  // Every record's stored inverse satisfies the contract rule: within
  // 1e-5 per component of the freshly computed exact inverse (and within
  // the 5e-7 storage step by construction).
  for (const t of chain) {
    const exact = inverse(t.matrix);
    for (let i = 0; i < 6; i++) {
      near(t.inverse[i], exact[i], `${t.id} stored inverse[${i}]`);
    }
  }
  // Exact-inverse chain round-trips within the 1e-5pt conformance bound.
  const exactBwd = inverse(fwd);
  nearPt(apply(exactBwd, apply(fwd, p)), p, 'exact-inverse chain round-trip');
  // A chain of 6dp-rounded stored inverses accumulates storage rounding:
  // ~5e-7 per step amplified by intermediate magnitudes (~1400 units of
  // raster here). Asserted bound 1e-3pt — still ~2000x under the 2pt
  // overlay budget; never mistaken for the exact-pair 1e-5pt bound.
  const [bx, by] = apply(bwd, apply(fwd, p));
  const storedErr = Math.max(Math.abs(bx - p[0]), Math.abs(by - p[1]));
  assert.ok(
    storedErr <= 1e-3,
    `stored-inverse chain error ${storedErr}pt exceeds documented bound`,
  );
  // Same destination as the direct math helper.
  nearMat(fwd, pageToOcr(built, 1.5, [500, 60], [2, 2]), 'chain vs pageToOcr');
  const directInv = inverse(pageToOcr(built, 1.5, [500, 60], [2, 2]));
  for (let i = 0; i < 6; i++) {
    assert.ok(
      Math.abs(bwd[i] - directInv[i]) <= 1e-3,
      `chain inverse[${i}] ${bwd[i]} vs ${directInv[i]} beyond documented bound`,
    );
  }
  nearMat(
    rasterToCanonical(built, 1.5),
    compose(pageToCanonical(built), inverse(pageToRaster(built, 1.5))),
    'rasterToCanonical',
  );
  nearMat(
    ocrToCanonical(built, 1.5, [500, 60], [2, 2]),
    compose(pageToCanonical(built), inverse(pageToOcr(built, 1.5, [500, 60], [2, 2]))),
    'ocrToCanonical',
  );
});

// ---------------------------------------------------------------------------
// F09 genus — skewed text transform produces a polygon, not an axis box
// ---------------------------------------------------------------------------

test('skewed text matrix maps a rect to a parallelogram polygon', () => {
  const { tm, rect, expected_polygon, expected_bounds } = EXPECTED.skew;
  const poly = transformPolygon(tm, rect);
  for (let i = 0; i < poly.length; i++) {
    nearPt(poly[i], expected_polygon[i], `skew vertex ${i}`);
  }
  const bounds = polygonBounds(poly);
  for (let i = 0; i < 4; i++) near(bounds[i], expected_bounds[i], `bounds[${i}]`);
  // The polygon is not its own axis-aligned bounds: a reader that emitted
  // the bounds box would report geometry the transform never produced.
  const boundCorners = boxPolygon(bounds).map((p) => `${p[0]},${p[1]}`);
  const polyCorners = poly.map((p) => `${p[0]},${p[1]}`);
  assert.ok(
    boundCorners.some((c) => !polyCorners.includes(c)),
    'skewed quad must differ from its axis-aligned bounds',
  );
  // The transformed polygon embeds cleanly as estimated geometry.
  const g = makeGeometry({
    precision: 'estimated',
    polygon: poly,
    transformIds: [],
    basis: 'skewed text extent quad',
  });
  assert.equal(g.polygon.length, 4);
});

// ---------------------------------------------------------------------------
// F10 genus — missingness stays missing (I04/I11)
// ---------------------------------------------------------------------------

test('absent geometry stays absent; no invented precise anchor', () => {
  // Readers that cannot supply geometry get page_only/unknown with a null
  // polygon — the package provides no path to fabricate one.
  for (const precision of ['page_only', 'unknown']) {
    const g = makeGeometry({
      precision,
      polygon: null,
      transformIds: [],
      basis: 'reader supplied no positional data',
    });
    assert.equal(g.polygon, null);
    assert.equal(g.precision, precision);
  }
  // Malformed reader output is rejected, never defaulted.
  assert.equal(
    code(() => makeGeometry({ precision: 'precise', polygon: null, transformIds: [], basis: 'x' })),
    'GEOMETRY',
  );
  assert.equal(
    code(() =>
      makeGeometry({
        precision: 'exact',
        polygon: [
          [0, 0],
          [1, 0],
          [1, 1],
        ],
        transformIds: [],
        basis: 'x'.repeat(2001),
      }),
    ),
    'GEOMETRY',
  );
});

// ---------------------------------------------------------------------------
// Storage hygiene: 6dp rounding, finite only, negative zero normalized
// ---------------------------------------------------------------------------

test('transform numbers round to 6dp and normalize negative zero', () => {
  assert.equal(round6(-0), 0);
  assert.equal(Object.is(round6(-0), -0), false);
  assert.equal(round6(1.23456789), 1.234568);
  const t = makeTransform({
    id: 't_round',
    pageIndex: 0,
    fromSpace: 'a',
    toSpace: 'b',
    matrix: [1.0000004, -0, 0, 1, -0.0000004, 2.9999999],
    operation: 'raster_scale',
    precision: 'exact',
    source: 'rounding check',
  });
  assert.deepEqual(t.matrix, [1, 0, 0, 1, 0, 3]);
  assert.ok(
    t.matrix.every((v) => !Object.is(v, -0)),
    'no negative zeros stored',
  );
  assert.ok(
    t.inverse.every((v) => Number.isFinite(v)),
    'inverse stays finite',
  );
  // Contract inverse check: stored pair composes to identity on extent.
  const err = code(() =>
    makeTransform({
      id: 't_extreme',
      pageIndex: 0,
      fromSpace: 'a',
      toSpace: 'b',
      matrix: [1e9, 0, 0, 1e-9, 0, 0],
      operation: 'raster_scale',
      precision: 'exact',
      source: 'round-off amplifier',
      extent: [
        [0, 0],
        [1e6, 1e6],
      ],
    }),
  );
  assert.equal(err, 'TRANSFORM', 'extreme round-off amplification rejected');
});

// ---------------------------------------------------------------------------
// Acceptance-harness shape: this suite itself reports structured counts
// ---------------------------------------------------------------------------

test('suite exercises every F07-F10 genus and both invariants', () => {
  // Documentation test: the suite covers the contract's fixture families.
  assert.ok(EXPECTED.pages['geometry-0'], 'F07 expectations present');
  assert.ok(EXPECTED.userunit['10'], 'F08 expectations present');
  assert.ok(EXPECTED.skew.expected_polygon.length === 4, 'F09 analytic genus');
  assert.ok(
    EXPECTED.clip.cases.length >= 5,
    'F10/missingness + clipping genus present',
  );
});
