#!/usr/bin/env python3
"""Generate contract artifacts from the single authoritative schema.

Reads ``planning/contracts/inkflip.schema.json`` (JSON Schema draft 2020-12,
schema version 1.0.0) and emits:

* ``packages/contracts/schema/inkflip.schema.json`` — byte-identical copy.
* ``native/inkflip/contracts/schema/inkflip.schema.json`` — byte-identical
  copy consumed by ``native/inkflip/contracts/core.py``.
* ``packages/contracts/src/generated/types.ts`` — TypeScript structural
  types (same generator rules as the delivered ``tools/generate_types.py``).
* ``packages/contracts/src/generated/schema-check.ts`` — precompiled
  structural validator. This is the static-Ajv equivalent: the schema is
  compiled to code at generation time, so validating an untrusted report
  never compiles, parses or fetches a schema at runtime.

Only the closed keyword set actually used by the canonical schema is
supported; anything else fails generation rather than silently
approximating. ``--check`` regenerates in memory and exits nonzero on any
drift, which is also the determinism check. No dependencies, no network.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / 'planning' / 'contracts' / 'inkflip.schema.json'
OUTPUT_PATHS = (
    'packages/contracts/schema/inkflip.schema.json',
    'native/inkflip/contracts/schema/inkflip.schema.json',
    'packages/contracts/src/generated/types.ts',
    'packages/contracts/src/generated/schema-check.ts',
)
TYPE_HEADER = (
    '// GENERATED by scripts/generate_contracts.py from '
    'planning/contracts/inkflip.schema.json. Do not edit.\n'
    '// Structural types only; validate cross-references, bounds and evidence '
    'semantics at runtime.\n'
    '// Schema {version}; source sha256 {digest}.'
)
CHECK_HEADER = (
    '// GENERATED by scripts/generate_contracts.py from '
    'planning/contracts/inkflip.schema.json. Do not edit.\n'
    '// Precompiled JSON Schema (draft 2020-12) structural validation. The\n'
    '// schema is compiled to code at generation time; validating untrusted\n'
    '// report data never compiles, parses or fetches a schema at runtime.\n'
    '// Schema {version}; source sha256 {digest}.'
)

# JSON Schema keywords the generator understands; anything else is rejected.
KNOWN = {
    '$schema', '$id', '$defs', '$ref', 'title', 'description', 'type',
    'const', 'enum', 'oneOf', 'anyOf', 'allOf', 'properties', 'required',
    'additionalProperties', 'items', 'prefixItems', 'minItems', 'maxItems',
    'uniqueItems', 'minimum', 'maximum', 'exclusiveMinimum',
    'exclusiveMaximum', 'minLength', 'maxLength', 'pattern', 'format',
    'default', 'contentEncoding', 'contentMediaType',
}


def schema_digest() -> str:
    return hashlib.sha256(SCHEMA.read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# TypeScript structural types (ported from planning/tools/generate_types.py)
# ---------------------------------------------------------------------------

def ts(s: dict | bool) -> str:
    if isinstance(s, bool):
        return 'unknown' if s else 'never'
    unknown = set(s) - KNOWN
    if unknown:
        raise ValueError(f'Unsupported schema keywords: {sorted(unknown)}')
    if '$ref' in s:
        if not s['$ref'].startswith('#/$defs/'):
            raise ValueError('Only local definitions permitted')
        return s['$ref'].split('/')[-1]
    if 'const' in s:
        return json.dumps(s['const'], ensure_ascii=False)
    if 'enum' in s:
        return ' | '.join(
            json.dumps(v, ensure_ascii=False) for v in s['enum']
        )
    for kind, sep in [('oneOf', ' | '), ('anyOf', ' | '), ('allOf', ' & ')]:
        if kind in s:
            return '(' + sep.join(ts(x) for x in s[kind]) + ')'
    t = s.get('type')
    if isinstance(t, list):
        return '(' + ' | '.join(ts(dict(s, type=x)) for x in t) + ')'
    if t in ('number', 'integer'):
        return 'number'
    if t == 'string':
        return 'string'
    if t == 'boolean':
        return 'boolean'
    if t == 'null':
        return 'null'
    if t == 'array':
        if 'prefixItems' in s:
            items = s['prefixItems']
            n = len(items)
            if s.get('minItems') != n or s.get('maxItems') != n:
                raise ValueError('Nonfixed tuple unsupported')
            return '[' + ', '.join(ts(x) for x in items) + ']'
        child = ts(s.get('items', True))
        if (
            s.get('minItems') == s.get('maxItems')
            and 'minItems' in s
            and s['minItems'] <= 12
        ):
            return '[' + ', '.join([child] * s['minItems']) + ']'
        return 'Array<' + child + '>'
    if t == 'object':
        fields = []
        required = set(s.get('required', []))
        for key, child in s.get('properties', {}).items():
            fields.append(
                json.dumps(key)
                + ('' if key in required else '?')
                + ': '
                + ts(child)
                + ';'
            )
        ap = s.get('additionalProperties', True)
        if ap is not False:
            raise ValueError('Only closed domain objects supported')
        return '{ ' + ' '.join(fields) + ' }'
    raise ValueError(f'Unsupported schema node: {s}')


def generate_types(schema: dict, header: str) -> str:
    lines = [header]
    for name, value in schema['$defs'].items():
        if not re.fullmatch(r'[A-Za-z_][A-Za-z_0-9]*', name):
            raise ValueError('Invalid TS definition name')
        lines.append('export type ' + name + ' = ' + ts(value) + ';')
    lines.append(
        'export type InkflipArtifact = '
        + ts(
            {
                k: v
                for k, v in schema.items()
                if k not in ('$defs', '$schema', '$id', 'title', 'description')
            }
        )
        + ';'
    )
    return '\n\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Precompiled structural validator
# ---------------------------------------------------------------------------

TYPE_GUARD = {
    'string': "typeof v === 'string'",
    'number': "typeof v === 'number'",
    'integer': "typeof v === 'number' && Number.isInteger(v)",
    'boolean': "typeof v === 'boolean'",
    'object': "typeof v === 'object' && v !== null && !Array.isArray(v)",
    'array': 'Array.isArray(v)',
    'null': 'v === null',
}
STRING_KEYS = ('minLength', 'maxLength', 'pattern', 'format')
NUMBER_KEYS = ('minimum', 'maximum', 'exclusiveMinimum', 'exclusiveMaximum')
ARRAY_KEYS = ('items', 'prefixItems', 'minItems', 'maxItems', 'uniqueItems')
OBJECT_KEYS = ('properties', 'required', 'additionalProperties')
# Formats the pinned jsonschema FormatChecker actually registers checkers for.
CHECKED_FORMATS = {'uuid'}


class Emitter:
    """Emit one TypeScript function per schema node."""

    def __init__(self, schema: dict):
        self.schema = schema
        self.out: list[str] = []
        self.names: dict[int, str] = {}
        self.patterns: dict[str, str] = {}  # RE name -> pattern
        self.counter = 0
        self.queue: list[tuple[str, dict]] = []

    @staticmethod
    def push(lines: list[str], indent: int, text: str) -> None:
        lines.append('  ' * indent + text)

    def fn_for(self, node: dict) -> str:
        if '$ref' in node:
            if len(node) > 1:
                raise ValueError(
                    '$ref with sibling keywords is unsupported: '
                    f'{sorted(node)}'
                )
            ref = node['$ref']
            if not ref.startswith('#/$defs/'):
                raise ValueError(f'Only local definitions permitted: {ref}')
            name = ref.split('/')[-1]
            if not re.fullmatch(r'[A-Za-z_][A-Za-z_0-9]*', name):
                raise ValueError(f'Invalid $ref name: {ref}')
            return f'check_{name}'
        key = id(node)
        if key not in self.names:
            self.names[key] = f'c{self.counter}'
            self.counter += 1
            self.queue.append((self.names[key], node))
        return self.names[key]

    def emit_all(self) -> str:
        for name, sub in self.schema['$defs'].items():
            self.names[id(sub)] = f'check_{name}'
            self.queue.append((f'check_{name}', sub))
        root_node = {
            k: v
            for k, v in self.schema.items()
            if k in KNOWN and k != '$defs'
        }
        self.queue.append(('check_root', root_node))
        while self.queue:
            name, node = self.queue.pop(0)
            self.emit_function(name, node)
        pattern_lines = [
            f'const {name} = new RegExp({json.dumps(p)});'
            for name, p in self.patterns.items()
        ]
        return '\n'.join(pattern_lines) + '\n\n' + '\n\n'.join(self.out)

    def emit_function(self, name: str, s: dict) -> None:
        if not isinstance(s, dict):
            raise ValueError(f'Non-object schema node under {name}')
        unknown = set(s) - KNOWN
        if unknown:
            raise ValueError(
                f'Unsupported schema keywords at {name}: {sorted(unknown)}'
            )
        lines = [
            f'function {name}(v: unknown, path: string, '
            'errs: SchemaIssue[]): void {'
        ]
        t = s.get('type')
        if isinstance(t, list):
            cond = ' || '.join(f'({TYPE_GUARD[x]})' for x in t)
            self.push(
                lines, 1,
                f'if (!({cond})) {{ errs.push({{ path, message: '
                f'{json.dumps("expected type " + "|".join(t))} }}); return; }}',
            )
        elif t is not None:
            if t not in TYPE_GUARD:
                raise ValueError(f'Unsupported type {t!r} at {name}')
            self.push(
                lines, 1,
                f'if (!({TYPE_GUARD[t]})) {{ errs.push({{ path, message: '
                f'{json.dumps("expected " + t)} }}); return; }}',
            )
        if 'const' in s:
            lit = json.dumps(s['const'], ensure_ascii=False)
            self.push(
                lines, 1,
                f'if (!eq(v, {lit})) errs.push({{ path, message: '
                f'{json.dumps("expected const " + lit[:60])} }});',
            )
        if 'enum' in s:
            lits = json.dumps(s['enum'], ensure_ascii=False)
            self.push(
                lines, 1,
                f'if (!({lits}).some((x) => eq(v, x))) '
                'errs.push({ path, message: "not in enum" });',
            )
        guards = (
            (
                NUMBER_KEYS,
                None if t in ('number', 'integer') else "typeof v === 'number'",
                self.emit_numeric,
            ),
            (
                STRING_KEYS,
                None if t == 'string' else "typeof v === 'string'",
                self.emit_string,
            ),
            (
                ARRAY_KEYS,
                None if t == 'array' else 'Array.isArray(v)',
                self.emit_array,
            ),
            (
                OBJECT_KEYS,
                None
                if t == 'object'
                else "typeof v === 'object' && v !== null && !Array.isArray(v)",
                self.emit_object,
            ),
        )
        for keys, guard, emit in guards:
            if any(k in s for k in keys):
                if guard is None:
                    emit(s, lines, 1)
                else:
                    self.push(lines, 1, f'if ({guard}) {{')
                    emit(s, lines, 2)
                    self.push(lines, 1, '}')
        for comb in ('anyOf', 'oneOf'):
            if comb in s:
                self.emit_combinator(s, comb, lines)
        if 'allOf' in s:
            for child in s['allOf']:
                self.push(lines, 1, f'{self.fn_for(child)}(v, path, errs);')
        lines.append('}')
        self.out.append('\n'.join(lines))

    def emit_numeric(self, s: dict, lines: list[str], ind: int) -> None:
        for key, op in (
            ('minimum', '<'),
            ('maximum', '>'),
            ('exclusiveMinimum', '<='),
            ('exclusiveMaximum', '>='),
        ):
            if key in s:
                bound = json.dumps(s[key])
                self.push(
                    lines, ind,
                    f'if (v {op} {bound}) errs.push({{ path, message: '
                    f'{json.dumps(key + " violated")} }});',
                )

    def emit_string(self, s: dict, lines: list[str], ind: int) -> None:
        if 'minLength' in s:
            self.push(
                lines, ind,
                f'if (strlen(v) < {s["minLength"]}) errs.push({{ path, '
                'message: "minLength violated" });',
            )
        if 'maxLength' in s:
            self.push(
                lines, ind,
                f'if (strlen(v) > {s["maxLength"]}) errs.push({{ path, '
                'message: "maxLength violated" });',
            )
        if 'pattern' in s:
            name = f'RE{len(self.patterns)}'
            if s['pattern'] not in self.patterns.values():
                self.patterns[name] = s['pattern']
            re_name = next(
                k for k, v in self.patterns.items() if v == s['pattern']
            )
            self.push(
                lines, ind,
                f'if (!testPattern({re_name}, v)) errs.push({{ path, '
                'message: "pattern violated" });',
            )
        if 'format' in s:
            fmt = s['format']
            if fmt in CHECKED_FORMATS:
                self.push(
                    lines, ind,
                    'if (!isUuid(v)) errs.push({ path, message: '
                    '"format uuid violated" });',
                )
            else:
                # Unregistered upstream (e.g. date-time): always conforms.
                self.push(
                    lines, ind,
                    f'// format {json.dumps(fmt)} unregistered in pinned '
                    'jsonschema; always conforms (parity)',
                )

    def emit_array(self, s: dict, lines: list[str], ind: int) -> None:
        if 'minItems' in s:
            self.push(
                lines, ind,
                f'if (v.length < {s["minItems"]}) errs.push({{ path, '
                'message: "minItems violated" });',
            )
        if 'maxItems' in s:
            self.push(
                lines, ind,
                f'if (v.length > {s["maxItems"]}) errs.push({{ path, '
                'message: "maxItems violated" });',
            )
        if s.get('uniqueItems'):
            self.push(
                lines, ind,
                'if (!allUnique(v)) errs.push({ path, message: '
                '"uniqueItems violated" });',
            )
        if 'prefixItems' in s:
            for i, child in enumerate(s['prefixItems']):
                fn = self.fn_for(child)
                self.push(
                    lines, ind,
                    f'if (v.length > {i}) {fn}(v[{i}], path + "/{i}", errs);',
                )
        elif 'items' in s:
            fn = self.fn_for(s['items'])
            self.push(
                lines, ind,
                'for (let i = 0; i < v.length; i++) '
                f'{fn}(v[i], path + "/" + i, errs);',
            )

    def emit_object(self, s: dict, lines: list[str], ind: int) -> None:
        props = s.get('properties', {})
        self.push(
            lines, ind, 'const o = v as Record<string, unknown>;'
        )
        for key in s.get('required', []):
            self.push(
                lines, ind,
                f'if (!({json.dumps(key)} in o)) errs.push({{ path: path + '
                f'{json.dumps("/" + key)}, message: '
                f'{json.dumps("missing required " + key)} }});',
            )
        for key, child in props.items():
            fn = self.fn_for(child)
            self.push(
                lines, ind,
                f'if ({json.dumps(key)} in o) {fn}(o[{json.dumps(key)}], '
                f'path + {json.dumps("/" + key)}, errs);',
            )
        if s.get('additionalProperties') is False:
            known = json.dumps(sorted(props))
            self.push(lines, ind, 'for (const k of Object.keys(o)) {')
            self.push(
                lines, ind + 1,
                f'if (!({known}).includes(k)) errs.push({{ path: path + '
                '"/" + k, message: "additional property" });',
            )
            self.push(lines, ind, '}')

    def emit_combinator(self, s: dict, comb: str, lines: list[str]) -> None:
        self.push(lines, 1, '{')
        self.push(lines, 2, 'let matched = 0;')
        for child in s[comb]:
            fn = self.fn_for(child)
            self.push(lines, 2, '{')
            self.push(lines, 3, 'const inner: SchemaIssue[] = [];')
            self.push(lines, 3, f'{fn}(v, path, inner);')
            self.push(lines, 3, 'if (inner.length === 0) matched++;')
            self.push(lines, 2, '}')
        if comb == 'anyOf':
            self.push(
                lines, 2,
                'if (matched === 0) errs.push({ path, message: '
                '"no anyOf alternative matched" });',
            )
        else:
            self.push(
                lines, 2,
                'if (matched !== 1) errs.push({ path, message: '
                '"oneOf alternatives matched " + matched + " times" });',
            )
        self.push(lines, 1, '}')


VALIDATOR_HELPERS = '''export interface SchemaIssue {
  path: string;
  message: string;
}

/**
 * Structural validation of a decoded JSON value against the compiled schema.
 * Returns one entry per violation; an empty list means the value is
 * structurally valid (semantic contract checks still apply).
 */
export function checkSchema(value: unknown): SchemaIssue[] {
  const errs: SchemaIssue[] = [];
  check_root(value, '#', errs);
  return errs;
}

/** Deep equality matching the Python validator (booleans are not numbers). */
function eq(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (
    typeof a !== 'object' || a === null ||
    typeof b !== 'object' || b === null
  ) {
    return false;
  }
  const aa = Array.isArray(a);
  if (aa !== Array.isArray(b)) return false;
  if (aa) {
    const x = a as unknown[];
    const y = b as unknown[];
    if (x.length !== y.length) return false;
    for (let i = 0; i < x.length; i++) {
      if (!eq(x[i], y[i])) return false;
    }
    return true;
  }
  const xo = a as Record<string, unknown>;
  const yo = b as Record<string, unknown>;
  const keys = Object.keys(xo);
  if (keys.length !== Object.keys(yo).length) return false;
  for (const k of keys) {
    if (!(k in yo) || !eq(xo[k], yo[k])) return false;
  }
  return true;
}

function allUnique(a: unknown[]): boolean {
  for (let i = 0; i < a.length; i++) {
    for (let j = i + 1; j < a.length; j++) {
      if (eq(a[i], a[j])) return false;
    }
  }
  return true;
}

/** Code-point length, matching Python len() on str. */
function strlen(s: string): number {
  let n = 0;
  for (const _ch of s) n++;
  return n;
}

/** Python re.search '$' also matches before a single trailing newline. */
function testPattern(re: RegExp, v: string): boolean {
  return re.test(v) || (v.endsWith('\\n') && re.test(v.slice(0, -1)));
}

/** jsonschema is_uuid: UUID-parseable with hyphens at 8/13/18/23. */
function isUuid(v: string): boolean {
  return /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(v);
}
'''


def generate_validator(schema: dict, header: str) -> str:
    emitter = Emitter(schema)
    body = emitter.emit_all()
    return header + '\n\n' + VALIDATOR_HELPERS + '\n' + body + '\n'


def render_all() -> dict[str, str]:
    schema_text = SCHEMA.read_text()
    schema = json.loads(schema_text)
    digest = schema_digest()
    version = '1.0.0'
    return {
        'packages/contracts/schema/inkflip.schema.json': schema_text,
        'native/inkflip/contracts/schema/inkflip.schema.json': schema_text,
        'packages/contracts/src/generated/types.ts': generate_types(
            schema,
            TYPE_HEADER.replace('{version}', version).replace(
                '{digest}', digest
            ),
        ),
        'packages/contracts/src/generated/schema-check.ts': generate_validator(
            schema,
            CHECK_HEADER.replace('{version}', version).replace(
                '{digest}', digest
            ),
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--check',
        action='store_true',
        help='verify committed outputs match regeneration; exit nonzero on drift',
    )
    args = parser.parse_args()
    outputs = render_all()
    if args.check:
        drift = [
            path
            for path, content in outputs.items()
            if not (ROOT / path).exists() or (ROOT / path).read_text() != content
        ]
        if drift:
            for path in drift:
                print(f'drift: {path}', file=sys.stderr)
            raise SystemExit(
                'Generated contract artifacts drifted; '
                'run scripts/generate_contracts.py'
            )
        print('Generated contract artifacts match the authoritative schema')
        return
    for path in OUTPUT_PATHS:
        target = ROOT / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(outputs[path])
        print(path)


if __name__ == '__main__':
    main()
