// Labeled interaction reference. Every displayed raw amount is read from the
// actual native report, never a special case keyed to an uploaded filename.
const tabs=[...document.querySelectorAll('[data-mode]')],panel=document.querySelector('#evidence-panel'),paper=document.querySelector('#paper-view'),reading=document.querySelector('#reading-view'),dialog=document.querySelector('#dialog'),detail=document.querySelector('#finding-detail');
let mode='page',returnFocus=null,report=null;
function setMode(next,focus=false){mode=next;panel.classList.toggle('compare',next==='compare');paper.hidden=next==='reading';reading.hidden=next==='page';for(const t of tabs){const yes=t.dataset.mode===next;t.setAttribute('aria-selected',String(yes));t.tabIndex=yes?0:-1;if(yes&&focus)t.focus();}panel.setAttribute('aria-labelledby','tab-'+next);document.querySelector('#announcement').textContent=next==='page'?'Actual prepared page crop shown.':next==='reading'?'Actual prepared PDFium reading shown.':'Both actual representations shown. This is not live browser processing.';}
for(const t of tabs){t.addEventListener('click',()=>setMode(t.dataset.mode));t.addEventListener('keydown',e=>{let i=tabs.indexOf(t);if(e.key==='ArrowRight')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft')i=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();setMode(tabs[i].dataset.mode,true);});}
function show(title,nodes){returnFocus=document.activeElement;document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-body').replaceChildren(...nodes);dialog.showModal();document.querySelector('#close').focus();}
function el(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function link(text,path){const a=el('a',text,'download');a.href=path;a.download='';return a;}
function close(){dialog.close();returnFocus?.focus();}document.querySelector('#close').addEventListener('click',close);dialog.addEventListener('cancel',()=>queueMicrotask(()=>returnFocus?.focus()));
document.querySelector('#finding').addEventListener('click',e=>{detail.hidden=!detail.hidden;e.currentTarget.setAttribute('aria-expanded',String(!detail.hidden));});
document.querySelector('#try').addEventListener('click',()=>{setMode('compare');document.querySelector('.stage').scrollIntoView({block:'center'});tabs[2].focus();});
document.querySelector('#sample-amount').addEventListener('click',()=>{setMode('compare');document.querySelector('.stage').scrollIntoView({block:'center'});tabs[2].focus();});
document.querySelector('#file-flow').addEventListener('click',()=>show('Your file, on your device',[el('p','This is an interaction reference. It does not open or process personal files.'),el('p','The finished flow is: choose a PDF locally → select pages or a region → compare named readings → inspect → preview and export. Model preparation, cancellation and incomplete checks stay visible.'),el('p','The full browser own-file path, privacy capture and device limits must pass G1. The native evidence here is not that proof.')]));
document.querySelector('#show-coverage').addEventListener('click',()=>show('Checked does not mean correct',[el('p','In this prepared native report, PDFium text extraction and Tesseract selected-crop OCR completed. Automatic alignment did not run.'),el('p','The report is partial. The selected crop is supplied explicitly, not automatically localized by the browser. Other source text is intentionally omitted from the selected report.'),el('p','No result here certifies safety, completeness or which reading is right.')]));
document.querySelector('#export').addEventListener('click',()=>show('Preview this example export',[el('p','Prepared native evidence · not live browser output'),el('p','Included: the two selected raw readings, original rendered crop, exact readers/settings, document hash, coordinate records and check coverage.'),el('p','Excluded: full source PDF, filename, unrelated text and model/runtime binaries. This evidence report requires the original PDF and reader environment for replay.'),link('Download machine-readable JSON','../contracts/examples/valid/native-evidence.inkflip.json'),link('Download script-free HTML','../examples/native-evidence.html')]));
(globalThis.__PREPARED_REFERENCE_REPORT__ ? Promise.resolve(globalThis.__PREPARED_REFERENCE_REPORT__) : fetch('../contracts/examples/valid/native-evidence.inkflip.json',{credentials:'omit'}).then(r=>{if(!r.ok)throw new Error('Prepared report unavailable');return r.json();})).then(r=>{report=r;const native=r.occurrences.find(o=>o.reader_id==='pdfium')||r.occurrences[0];const nativeReader=r.readers.find(x=>x.id===native.reader_id);const ocr=r.occurrences.find(o=>o.reader_id!==native.reader_id);document.querySelector('#native-reading').textContent=native.raw_text;document.querySelector('#reader-label').textContent=nativeReader.name+' '+nativeReader.version;document.querySelector('#detail-native').textContent=native.raw_text;document.querySelector('#detail-ocr').textContent=ocr.raw_text.trim()+' · Tesseract5.5.0';}).catch(error=>{document.querySelector('#reader-label').textContent='Prepared report unavailable';document.querySelector('#native-reading').textContent='Not checked';document.querySelector('#announcement').textContent=error.message;});

document.querySelector('#menu').addEventListener('click',()=>{const a=el('a','Examples','download');a.href='#examples';a.addEventListener('click',close);const b=el('a','What it checks','download');b.href='../architecture/CAPABILITIES.md';const c=el('a','Build package','download');c.href='../START_HERE.md';show('Explore Inkflip',[a,b,c]);});
