/**
 * Synthetic viewer document retained only for historical viewer/a11y tests
 * that still need its deterministic finding identities. Public demo entry
 * points load a captured gallery report instead.
 */
import type { ViewerDoc } from "../features/viewer/types";

export const EXAMPLE_DOC: ViewerDoc = {
  pages: [
    {
      index: 0,
      media_box: [0, 0, 612, 792],
      crop_box: [0, 0, 612, 792],
      effective_view_box: [0, 0, 612, 792],
      box_source: "media_box",
      user_unit: 1.0,
      rotation: 0,
      canonical_size_pt: [612, 792],
      raw_to_canonical_transform_id: "t_p0",
      limitations: ["OCR verification was not run on page 0."],
    },
    {
      index: 1,
      media_box: [0, 0, 612, 792],
      crop_box: [0, 0, 612, 792],
      effective_view_box: [0, 0, 612, 792],
      box_source: "media_box",
      user_unit: 1.0,
      rotation: 0,
      canonical_size_pt: [612, 792],
      raw_to_canonical_transform_id: "t_p1",
      limitations: [],
    },
  ],
  readers: [
    {
      id: "reader-pdfium",
      name: "PDFium",
      version: "149.0.7825.0",
      build: "pdfium-wasm",
      adapter_version: "1.0.0",
      method: "native_text",
      environment: "browser",
      settings: {
        normalization: "scalar-whitespace-v1",
        language: null,
        psm: null,
        render_reader_id: null,
        raster_dpi: null,
        annotation_mode: "none",
      },
      capabilities: [],
      model_hashes: [],
      limitations: [],
    },
    {
      id: "reader-pypdf",
      name: "pypdf",
      version: "6.18.0",
      build: "pypdf-wasm",
      adapter_version: "1.0.0",
      method: "native_text",
      environment: "browser",
      settings: {
        normalization: "scalar-whitespace-v1",
        language: null,
        psm: null,
        render_reader_id: null,
        raster_dpi: null,
        annotation_mode: "none",
      },
      capabilities: [],
      model_hashes: [],
      limitations: [],
    },
  ],
  occurrences: [
    {
      id: "occ-p0-dup1",
      reader_id: "reader-pdfium",
      page_index: 0,
      ordinal: 1,
      raw_text: "$1,000.00",
      normalized_text: "$1,000.00",
      normalization_map: [],
      geometry: {
        precision: "exact",
        space: "canonical_page",
        polygon: [
          [100, 150],
          [180, 150],
          [180, 170],
          [100, 170],
        ],
        transform_ids: [],
        basis: "pdfium_char_boxes",
      },
      engine_score: null,
      source_asset_id: null,
      raw_source_locator: "p0:line1",
      limitations: [],
    },
    {
      id: "occ-p0-dup2",
      reader_id: "reader-pdfium",
      page_index: 0,
      ordinal: 2,
      raw_text: "$1,000.00",
      normalized_text: "$1,000.00",
      normalization_map: [],
      geometry: {
        precision: "exact",
        space: "canonical_page",
        polygon: [
          [100, 350],
          [180, 350],
          [180, 370],
          [100, 370],
        ],
        transform_ids: [],
        basis: "pdfium_char_boxes",
      },
      engine_score: null,
      source_asset_id: null,
      raw_source_locator: "p0:line5",
      limitations: [],
    },
    {
      id: "occ-p0-pypdf1",
      reader_id: "reader-pypdf",
      page_index: 0,
      ordinal: 1,
      raw_text: "$10,000.00",
      normalized_text: "$10,000.00",
      normalization_map: [],
      geometry: {
        precision: "exact",
        space: "canonical_page",
        polygon: [
          [100, 150],
          [185, 150],
          [185, 170],
          [100, 170],
        ],
        transform_ids: [],
        basis: "pypdf_boxes",
      },
      engine_score: null,
      source_asset_id: null,
      raw_source_locator: "p0:block1",
      limitations: [],
    },
    {
      id: "occ-p1-item1",
      reader_id: "reader-pdfium",
      page_index: 1,
      ordinal: 1,
      raw_text: "Total Amount Due",
      normalized_text: "Total Amount Due",
      normalization_map: [],
      geometry: {
        precision: "exact",
        space: "canonical_page",
        polygon: [
          [120, 200],
          [240, 200],
          [240, 220],
          [120, 220],
        ],
        transform_ids: [],
        basis: "pdfium_char_boxes",
      },
      engine_score: null,
      source_asset_id: null,
      raw_source_locator: "p1:line2",
      limitations: [],
    },
    {
      id: "occ-p1-pagelevel",
      reader_id: "reader-pypdf",
      page_index: 1,
      ordinal: 2,
      raw_text: "Metadata font dictionary notice",
      normalized_text: "Metadata font dictionary notice",
      normalization_map: [],
      geometry: {
        precision: "page_only",
        space: "canonical_page",
        polygon: null,
        transform_ids: [],
        basis: "page_level_font_dict",
      },
      engine_score: null,
      source_asset_id: null,
      raw_source_locator: "p1:dict",
      limitations: ["Page-level property only; no localized bounding coordinates."],
    },
  ],
  findings: [
    {
      id: "finding-dup1",
      kind: "reading_difference",
      title: "Amount reads differently (occurrence #1)",
      explanation: "PDFium returned “$1,000.00”. pypdf returned “$10,000.00”.",
      page_index: 0,
      occurrence_ids: ["occ-p0-dup1", "occ-p0-pypdf1"],
      check_ids: ["chk-1"],
      alignment: "unique",
      region_id: "region-1",
      priority: "material_token",
      basis: "Exact coordinate alignment.",
      limitations: ["A difference does not establish which reading is correct."],
    },
    {
      id: "finding-dup2",
      kind: "reading_difference",
      title: "Amount reads differently (occurrence #2)",
      explanation: "Duplicate amount token at lower section of Page 1.",
      page_index: 0,
      occurrence_ids: ["occ-p0-dup2"],
      check_ids: ["chk-2"],
      alignment: "unique",
      region_id: "region-2",
      priority: "material_token",
      basis: "Exact coordinate alignment.",
      limitations: ["A difference does not establish which reading is correct."],
    },
    {
      id: "finding-page1-unknown",
      kind: "observed_structure",
      title: "Font metadata structure observation (Page 2)",
      explanation: "Font dictionary observation on Page 2 without localized coordinate bounding.",
      page_index: 1,
      occurrence_ids: ["occ-p1-pagelevel"],
      check_ids: ["chk-3"],
      alignment: "page_level",
      region_id: null,
      priority: "informational",
      basis: "Font dictionary parsing.",
      limitations: ["Page-level only; no localized bounding coordinates."],
    },
    {
      id: "finding-ambig-amounts",
      kind: "reading_difference",
      title: "Several locations could match this reading",
      explanation:
        "We could not select one location reliably. Compare the candidates without a precise-match claim.",
      page_index: 0,
      occurrence_ids: ["occ-p0-dup1", "occ-p0-dup2", "occ-p0-pypdf1"],
      check_ids: ["chk-1", "chk-2"],
      alignment: "ambiguous",
      region_id: null,
      priority: "ordinary",
      basis:
        "region-match-v1 bounded matching over retained reader occurrences; ambiguity reason tie.",
      limitations: ["A difference does not establish which reading is correct."],
    },
    {
      id: "finding-order-columns",
      kind: "observed_structure",
      title: "Same readings in a different emitted order",
      explanation:
        "The compared readers produced the same readings here in a different emitted sequence. This is an order difference — not a text difference and not, by itself, an accessibility verdict.",
      page_index: 0,
      occurrence_ids: ["occ-p0-dup1", "occ-p0-pypdf1"],
      check_ids: ["chk-1"],
      alignment: "not_applicable",
      region_id: null,
      priority: "informational",
      basis:
        "region-match-v1 bounded matching over retained reader occurrences; order-only difference (emission_order_differs, order distance 0.5000).",
      limitations: [
        "Reading-order differences do not establish an accessibility fault.",
      ],
    },
  ],
};

